FROM tbcp/centos

USER bootcamp

RUN sudo yum -y install \
    python3 \
    python3-pip \
    python3-venv \
    python3-all

RUN python3 -m pip install --upgrade --user pip setuptools wheel

ENV PATH /home/bootcamp/.local/bin:/usr/local/bin/python3:/usr/local/bin/pip3:$PATH
