FROM tbcp/ubuntu:latest

ENV DEBIAN_FRONTEND noninteractive

USER bootcamp

RUN sudo apt update && \
    sudo apt install -y --no-install-recommends apt-utils && \
    sudo apt install -y \
    python3 \
    python3-pip \
    python3-venv \
    python3-all \
    debhelper \
    dh-python

RUN python3 -m pip install --upgrade --user pip setuptools wheel

ENV PATH /home/bootcamp/.local/bin:/usr/local/bin/python3:/usr/local/bin/pip3:$PATH
